### ISSUE TITLE
NFS Server provisioner allocates 2x the PVC size for Segmentstore pod's tier2 disk space

### ISSUE THREAD

**Issue by deenav** [pravega/pravega-operator#109]
**Problem Description**
NFS Server provisioner allocates 2x the space requested (PVC size) for Segmentstore pods running on PKS cluster. We can create a PVC `pravega-tier2` storage for segmentstore pods by specifying the `storage` field in `pvc.yaml` as below. Here it is `250Gi` 

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pravega-tier2
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
```
```
# kubectl get pvc pravega-tier2 
NAME                     STATUS    VOLUME                                 CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pravega-tier2          Bound     pvc-723777d5-fca0-11e8-957d-005056ae1b75   250Gi      RWX        nfs             16h
```
But it looks like `pravega-segmentstore` pods are getting the tier2 disk space of 2x the PVC size. In my example it gets `~500Gb` instead of `250Gb`.

```
/opt/pravega # df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  49.1G      5.3G     41.3G  11% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     1.9G         0      1.9G   0% /sys/fs/cgroup
/dev/sda1                 2.9G      1.4G      1.3G  51% /dev/termination-log
10.100.200.148:/export/pvc-723777d5-fca0-11e8-957d-005056ae1b75
                               503.8G     13.6G    490.2G   3% /mnt/tier2
```

This issue needs more investigation to understand why the  NFS Server provisioner allocates 2x the space requested.
