### ISSUE TITLE
"example/cr-detailed.yaml" file contains invalid syntax for 'options' label

### ISSUE THREAD

**Issue by deenav** [pravega/pravega-operator#147]
"example/cr-detailed.yaml" file is an example `pravega.yaml` file for Pravega components & config parameters to be deployed. 

It should contain only one `options` block under `pravega` but currently there are three `options` block. Also one options parameters values are written as `integers` but it should be passed as `string` values.

Existing code snip
```
  options:
      pravegaservice.containerCount: 4
      pravegaservice.cacheMaxSize: 17179869184
      pravegaservice.zkSessionTimeoutMs: 10000
      attributeIndex.readBlockSize: 1048576
      readIndex.storageReadAlignment: 1048576
      durableLog.checkpointMinCommitCount: 300
      bookkeeper.bkAckQuorumSize: 4
      metrics.dynamicCacheSize: 100000
```

It should be modified as:

```
  options:
      pravegaservice.containerCount: "4"
      pravegaservice.cacheMaxSize: "17179869184"
      pravegaservice.zkSessionTimeoutMs: "10000"
      attributeIndex.readBlockSize: "1048576"
      readIndex.storageReadAlignment: "1048576"
      durableLog.checkpointMinCommitCount: "300"
      bookkeeper.bkAckQuorumSize: "4"
      metrics.dynamicCacheSize: "100000"
```
