### ISSUE TITLE
Documenting Serviceaccount, roles & clusterroles required for enabling external-connectivity for Pravega 

### ISSUE THREAD

**Issue by deenav** [pravega/pravega-operator#161]
**When enabling `external-connectivity` if the service account that is configured in the SegmentStore pod doesn't have proper permissions then we will encounter issue https://github.com/pravega/pravega/issues/3614 .** 

So it would be good to have a proper configuration (Serviceaccount, roles, clusterroles, etc ..) details documented in `README.md` page https://github.com/pravega/pravega-operator#enable-external-access.

As per the suggestion from @adrianmo, below are the steps to be followed for enabling `external-connectivity` 

1. Create a service account
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pravega-components
```
2. Create a role (make sure to use the correct namespace) 
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pravega-components
  namespace: "default"
rules:
- apiGroups: ["pravega.pravega.io"]
  resources: ["*"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get"]
```

3. Create the clusterrole
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pravega-components
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
```
4. Create rolebinding
```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pravega-components
subjects:
- kind: ServiceAccount
  name: pravega-components
roleRef:
  kind: Role
  name: pravega-components
  apiGroup: rbac.authorization.k8s.io
```
5. Create clusterrolebinding
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pravega-components
subjects:
- kind: ServiceAccount
  name: pravega-components
  namespace: default
roleRef:
  kind: ClusterRole
  name: pravega-components
  apiGroup: rbac.authorization.k8s.io
```
6. On the `PravegaCluster` manifest, configure the service accounts
```
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "example"
spec:
  bookkeeper:
    serviceAccountName: pravega-components
...
  pravega:
    controllerServiceAccountName: pravega-components
    segmentStoreServiceAccountName: pravega-components
...
```
