### ISSUE TITLE
Operator 0.4.0 does not allow different versions of bookkeeper and pravega image to be provisioned

### ISSUE THREAD

**Issue by pbelgundi** [pravega/pravega-operator#220]
### Description
With Operator 0.4.0, the provision for specifying the image versions for Pravega and Bookeeper separately has been removed and has been replaced by a single version field in the manifest file which is used for both the Pravega and the Bookkeeper images.

### Importance
It is a must-have fix as without it we would be unable to test a given Pravega version with a different Bookkeeper version.

### Location
Before 0.4.0, the image tag for Pravega and Bookkeeper could be separately specified as :-
```
bookkeeper:
  image:
    repository: pravega/bookkeeper
    tag: 0.5.0
    pullPolicy: Always

pravega:
  image:
    repository: pravega/pravega
    tag: 0.5.0
    pullPolicy: Always
 
```
In operator 0.4.0 this was modified and the version is now specified as :-
```
version: 0.5.0

bookkeeper:
  image:
    repository: pravega/bookkeeper

pravega:
  image:
    repository: pravega/pravega
```
