### ISSUE TITLE
Mixed up volume mounts for ledger and journal

### ISSUE THREAD

**Issue by jingjinglll** [pravega/pravega-operator#221]
### Description
Mixed up the volume mount names for Ledger and Journal. 
When enlarge ledgerVolumeRequest actual effect on journal Volume

### Location

`				VolumeMounts: []corev1.VolumeMount{
					{
						Name:      LedgerDiskName,
						MountPath: "/bk/journal",
					},
					{
						Name:      JournalDiskName,
						MountPath: "/bk/ledgers",
					},`

**Comment by pbelgundi** [comment]
It would help to have some context on this issue like, how it was reproduced.

**Comment by SomeshJoshi19** [comment]
The resource value allocated in `pravega.yaml` manifest for bookie/ledger gets reflected in bookie/journal and vice versa when checked inside the pod whereas `kubectl get pvc` shows manifest allocated values.

`pravega.yaml` manifest, resource allocation for bookkeeper: -
```
bookkeeper:
    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/bookkeeper
      tag: 0.5.0-2284.8c6c176
      pullPolicy: IfNotPresent

    replicas: 4
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"

    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 100Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 500Gi

      indexVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 30Gi
```

$ **kubectl get pvc**
```
NAME                                    STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cache-pravega-pravega-segmentstore-0    Bound     pvc-9cd374df-9bd6-11e9-afe1-005056ba632e   30Gi       RWO            standard       4h
cache-pravega-pravega-segmentstore-1    Bound     pvc-ba616ced-9bd6-11e9-afe1-005056ba632e   30Gi       RWO            standard       4h
cache-pravega-pravega-segmentstore-2    Bound     pvc-d6d2d79c-9bd6-11e9-afe1-005056ba632e   30Gi       RWO            standard       4h
data-pravega-example-zk-0               Bound     pvc-2f85975a-9bd4-11e9-afe1-005056ba632e   100Gi      RWO            standard       5h
data-pravega-example-zk-1               Bound     pvc-48ab88c2-9bd4-11e9-afe1-005056ba632e   100Gi      RWO            standard       5h
data-pravega-example-zk-2               Bound     pvc-65968696-9bd4-11e9-afe1-005056ba632e   100Gi      RWO            standard       5h
index-pravega-bookie-0                  Bound     pvc-9c94bca4-9bd6-11e9-afe1-005056ba632e   30Gi       RWO            standard       4h
index-pravega-bookie-1                  Bound     pvc-9ca7b8b4-9bd6-11e9-afe1-005056ba632e   30Gi       RWO            standard       4h
index-pravega-bookie-2                  Bound     pvc-9cb8a6d9-9bd6-11e9-afe1-005056ba632e   30Gi       RWO            standard       4h
index-pravega-bookie-3                  Bound     pvc-9cc95464-9bd6-11e9-afe1-005056ba632e   30Gi       RWO            standard       4h
journal-pravega-bookie-0                Bound     pvc-9c933621-9bd6-11e9-afe1-005056ba632e   500Gi      RWO            standard       4h
journal-pravega-bookie-1                Bound     pvc-9c9c1487-9bd6-11e9-afe1-005056ba632e   500Gi      RWO            standard       4h
journal-pravega-bookie-2                Bound     pvc-9cbdf47b-9bd6-11e9-afe1-005056ba632e   500Gi      RWO            standard       4h
journal-pravega-bookie-3                Bound     pvc-9cc38e9f-9bd6-11e9-afe1-005056ba632e   500Gi      RWO            standard       4h
ledger-pravega-bookie-0                 Bound     pvc-9c93d209-9bd6-11e9-afe1-005056ba632e   100Gi      RWO            standard       4h
ledger-pravega-bookie-1                 Bound     pvc-9ca2e9b3-9bd6-11e9-afe1-005056ba632e   100Gi      RWO            standard       4h
ledger-pravega-bookie-2                 Bound     pvc-9cb3ddcd-9bd6-11e9-afe1-005056ba632e   100Gi      RWO            standard       4h
ledger-pravega-bookie-3                 Bound     pvc-9cc64d36-9bd6-11e9-afe1-005056ba632e   100Gi      RWO            standard       4h
pravega-tier2                           Bound     pvc-de86fb5f-9bd5-11e9-a5ee-005056ba7391   1000Gi     RWX            nfs            5h
pvc-shaka-zulu-nfs-client-provisioner   Bound     pv-shaka-zulu-nfs-client-provisioner       10Mi       RWO                           5h
```
$ **kubectl exec -it pravega-bookie-1 -- /bin/bash**
```
[root@pravega-bookie-1 bookkeeper]# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          50G  3.1G   44G   7% /
tmpfs            64M     0   64M   0% /dev
tmpfs            16G     0   16G   0% /sys/fs/cgroup
/dev/sdf        493G   70M  492G   1% /bk/ledgers
/dev/sde         30G   44M   30G   1% /bk/index
/dev/sdb2        32G  4.1G   27G  14% /etc/hosts
/dev/sdg         99G   62M   99G   1% /bk/journal
/dev/sdc1        50G  3.1G   44G   7% /etc/hostname
shm              64M     0   64M   0% /dev/shm
tmpfs            16G   12K   16G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            16G     0   16G   0% /proc/acpi
tmpfs            16G     0   16G   0% /proc/scsi
tmpfs            16G     0   16G   0% /sys/firmware
```
