### ISSUE TITLE
Add segmentStoreSvcAnnotations isn't working : - not shown in svc of SS

### ISSUE THREAD

**Issue by Raghuveera-Rao** [pravega/pravega-operator#289]
Deployment details:

```
bookkeeper:0.6.0-2391.97363b3
pravega:0.6.0-2391.97363b3
openjdk:8
pravega/pravega-operator:0.4.2-rc2
pravega/zookeeper:0.2.4
pravega/zookeeper-operator:0.2.4
```

Pravega manifest used:-
```
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "pravega"
spec:
  externalAccess:
    enabled: true
    type: LoadBalancer
  version: 0.6.0-2391.97363b3
  zookeeperUri: "pravega-zk-0.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-1.pravega-zk-headless.default.svc.cluster.local:2181,pravega-zk-2.pravega-zk-headless.default.svc.cluster.local:2181"

  bookkeeper:
    serviceAccountName: pravega-components
    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/bookkeeper
      pullPolicy: Always

    replicas: 4
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "6Gi"
        cpu: "2000m"

    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 200Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 200Gi
indexVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 30Gi

    autoRecovery: true
    options:
      useHostNameAsBookieID: "true"
      minorCompactionThreshold: "0.4"
      minorCompactionInterval: "1800"
      majorCompactionThreshold: "0.8"
      majorCompactionInterval: "43200"
      isForceGCAllowWhenNoSpace: "true"
      diskUsageThreshold: "0.90"
      diskUsageWarnThreshold: "0.85"
      diskUsageLwmThreshold: "0.85"

  pravega:
    controllerSvcAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
    segmentStoreSvcAnnotations:
      service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "abc"
    controllerServiceAccountName: pravega-components
    segmentStoreServiceAccountName: pravega-components
    controllerReplicas: 2
    controllerResources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "3Gi"
        cpu: "2000m"
segmentStoreReplicas: 3
    segmentStoreResources:
      requests:
        memory: "4Gi"
        cpu: "2000m"
      limits:
        memory: "8Gi"
        cpu: "4000m"

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 30Gi

    image:
      repository: devops-repo.isus.emc.com:8116/nautilus/pravega
      pullPolicy: Always

    options:
      bookkeeper.bkWriteQuorumSize: "3"
      bookkeeper.bkAckQuorumSize: "3"
      pravegaservice.cacheMaxSize: "3221225472"
      pravegaservice.cacheMaxTimeSeconds: "600"
      rocksdb.writeBufferSizeMB: "64"
      rocksdb.readCacheSizeMB: "8"
      rocksdb.cacheBlockSizeKB: "32"
      writer.flushThresholdBytes: "67108864"
      writer.flushThresholdMillis: "2000"
      writer.maxFlushSizeBytes: "67108864"
      writer.minReadTimeoutMillis: "200"
      hdfs.blockSize: "67108864"
      pravegaservice.containerCount: "32"
      controller.containerCount: "32"
      pravegaservice.threadPoolSize: "30"
      controller.retention.bucketCount: "10"
      controller.service.asyncTaskPoolSize: "20"
      controller.retention.threadCount: "4"
      log.level: "INFO"
      metrics.dynamicCacheSize: "100000"
metrics.enableStatistics: "false"
      metrics.enableStatsDReporter: "false"
      metrics.statsdHost: "telegraph.default"
      metrics.statsdPort: "8125"
      metrics.enableInfluxDBReporter: "false"
      metrics.outputFrequencySeconds: "10"
      metrics.influxDBURI: "http://172.28.232.2:8086"
      controller.metrics.dynamicCacheSize: "100000"
      controller.metrics.enableStatistics: "false"
      controller.metrics.enableStatsDReporter: "false"
      controller.metrics.statsdHost: "telegraph.default"
      controller.metrics.statsdPort: "8125"
      controller.metrics.enableInfluxDBReporter: "false"
      controller.metrics.outputFrequencySeconds: "10"
      controller.metrics.influxDBURI: "http://172.28.232.2:8086"

    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
```

$kubectl get svc
```
NAME                                    TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                          AGE
kubernetes                              ClusterIP      10.100.200.1     <none>           443/TCP                          4h46m
pravega-bookie-headless                 ClusterIP      None             <none>           3181/TCP                         43m
pravega-pravega-controller              LoadBalancer   10.100.200.237   10.240.119.237   10080:30294/TCP,9090:30240/TCP   43m
pravega-pravega-segmentstore-0          LoadBalancer   10.100.200.51    10.240.119.238   12345:30439/TCP                  43m
pravega-pravega-segmentstore-1          LoadBalancer   10.100.200.186   10.240.119.241   12345:31515/TCP                  43m
pravega-pravega-segmentstore-2          LoadBalancer   10.100.200.111   10.240.119.244   12345:30690/TCP                  43m
pravega-pravega-segmentstore-headless   ClusterIP      None             <none>           12345/TCP                        43m
pravega-webhook-svc                     ClusterIP      10.100.200.60    <none>           443/TCP                          44m
pravega-zk-client                       ClusterIP      10.100.200.159   <none>           2181/TCP                         47m
pravega-zk-headless                     ClusterIP      None             <none>           2888/TCP,3888/TCP                47m
```
$kubectl describe svc pravega-pravega-segmentstore-0
```
Name:                     pravega-pravega-segmentstore-0
Namespace:                default
Labels:                   app=pravega-cluster
                          component=pravega-segmentstore
                          pravega_cluster=pravega
Annotations:              ncp/internal_ip_for_policy: 100.64.112.77
Selector:                 statefulset.kubernetes.io/pod-name=pravega-pravega-segmentstore-0
Type:                     LoadBalancer
IP:                       10.100.200.51
LoadBalancer Ingress:     10.240.119.238
Port:                     server  12345/TCP
TargetPort:               12345/TCP
NodePort:                 server  30439/TCP
Endpoints:                172.28.145.11:12345
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     32190
Events:                   <none>
```

The annotation is not reflected in svc `service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "abc"`
