### ISSUE TITLE
Helm chart should allow watch namespace to be passed in

### ISSUE THREAD

**Issue by maddisondavid** [pravega/pravega-operator#311]
### Description

Currently the Helm chart for the Pravega Operator will ONLY watch for Pravega resources in the same namespace that the operator is installed:
```
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```
https://github.com/pravega/pravega-operator/blob/master/charts/pravega-operator/templates/operator.yaml#L26-L30

The helm chart should provide a way of overriding this so that the operator can watch ALL namespaces (by passing in "") or another namespace different to the one the operator is installed in.

### Importance
`should-have` without this the operator installed by the Helm chart isn't as useful and doesn't act like a standard Kubernetes Operator.

### Location

https://github.com/pravega/pravega-operator/blob/master/charts/pravega-operator/templates/operator.yaml#L26-L30

### Suggestions for an improvement

Allow a `watchNamespace` value to be passed in.  If it exists then use it otherwise default to the current implementation. (However I would suggest that the default should REALLY be to watch all namespaces!)
