### ISSUE TITLE
Add an initContainer field to the PravegaClusterResource

### ISSUE THREAD

**Issue by sarlaccpit** [pravega/pravega-operator#37]
**Motivation:**

To facilitate the customizing of Pravega cluster installation, it would be very useful to have an initContainer "hook", such that one can inject files in the controller's runtime environment.   The concrete use of it for now, is the ability to provide plugin implementations (the auth handler being the primary one at the moment, I think).

**Proposal:**

```
 pravega:
    controllerReplicas: 1
    segmentStoreReplicas: 3

    plugins:  <-- new element
      images: [ "repohost/reponame/imagename:tag" ]  

    cacheVolumeClaimTemplate:
```

When the `plugin` element is seen,  the operator would do the following:

1. add an empty volume in the controller pod
2. map this volume to `/opt/pravega/plugin/lib` to an init-container spec of the main controller deployment spec, using the specified image from the plugins spec
3. map that same volume to the same location in the controller container itself.

Let k8 do the rest. :)

The requirement for the init-container image implementation is simply to:
1. contain a fat jar for the desired plugin to implement
2. have an entry point/command that automatically does a `cp` of the jar into `/opt/pravega/plugin/lib`.

This will allow the said jars files to eventually show up in the controller's main container's /opt/pravega/plugin/lib directory and be ready to use.

note: the proposal uses a list for images, as one could think there could be multiple init containers back to back which, according to k8 documentation, would execute one after the other in the order of the list.
