### ISSUE TITLE
Cannot configure AWS S3 Tier2 storage in Helm chart

### ISSUE THREAD

**Issue by ambye85** [pravega/pravega-operator#489]
I'd like to configure Pravega Tier2 storage to use AWS S3. My understanding from the [long term storage docs][1] is that any S3 compatible backend is supported. However, I can't seem to get this working in my Kubernetes cluster.

I'm using the following secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  ACCESS_KEY_ID: [AWS_ACCESS_KEY_ID]
  SECRET_KEY: [AWS_SECRET_ACCESS_KEY]
```

And the relevant Helm values for the Pravega cluster configuration:
```yaml
storage:
  longtermStorage:
    type: ecs
    ecs:
      configUri: https://s3.eu-west-2.amazonaws.com
      bucket: "my-aws-s3-bucket"
      prefix: "my-prefix"
      credentials: aws-credentials
```

Using the toy NFS example I can write to and read from a stream. However, with the above configuration the deployment of Pravega fails. Has anyone had any success with AWS S3 as a Tier2 storage?

  [1]: https://github.com/pravega/pravega-operator/blob/master/doc/longtermstorage.md#use-dell-emc-ecs-as-longtermstorage
