### ISSUE TITLE
Confusing behavior when trying to override Pravega helm chart `options` parameter

### ISSUE THREAD

**Issue by wxing1292** [pravega/pravega-operator#554]
### Description
when trying to override the `options` of Pravega helm chart, e.g. 

```bash
helm template pravega pravega/pravega --version=0.9.0 \
     --set options.controller.container.count=128 \
     --set options.pravegaservice.container.count=128 \
     --set options.pravegaservice.cache.size.max=4294967296 \
     --set options.pravegaservice.cache.time.seconds.max=600 \
     --timeout 15m --wait
```

the generated output looks confusing:
```yaml
    options:
      bookkeeper.ack.quorum.size: "3"
      bookkeeper.ensemble.size: "3"
      bookkeeper.write.outstanding.bytes.max: "33554432"
      bookkeeper.write.quorum.size: "3"
      bookkeeper.write.timeout.milliseconds: "60000"
      controller:
        container:
          count: 128
      controller.container.count: "8"
      controller.retention.bucket.count: "4"
      controller.retention.thread.count: "4"
      controller.service.asyncTaskPool.size: "20"
      hdfs.block.size: "67108864"
      log.level: INFO
      pravegaservice:
        cache:
          size:
            max: 4294967296
          time:
            seconds:
              max: 600
        container:
          count: 128
      pravegaservice.cache.size.max: "1073741824"
      pravegaservice.cache.time.seconds.max: "600"
      pravegaservice.container.count: "8"
      writer.flush.size.bytes.max: "67108864"
      writer.flush.threshold.bytes: "67108864"
```

specifically
```yaml
      controller:
        container:
          count: 128
      controller.container.count: "8"
```      

not sure which config is actually used, 128 vs 8.

### Importance

above looks like a blocker

### Location

https://github.com/pravega/pravega-operator/blob/v0.5.2/charts/pravega/values.yaml#L120
above settings probably should looks like
```yaml
options:
    controller:
        container:
            count: 8
```

instead of

```yaml
options:
    controller.container.count: "8"
```

### Suggestions for an improvement

see above
