### ISSUE TITLE
Ensure data protection (DU/DL)

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega-operator#60]
Operator should ensure that components (e.g. bookies) are deployed in a reasonable way from a data protection perspective.   Kubernetes has features including [anti-affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity-beta-feature), multi-zone, and [pod disruption budgets](https://kubernetes.io/docs/tasks/run-application/configure-pdb/).

Achieving adequate data protection likely has deployment- and upgrade-time considerations, e.g. anti-affinity to prevent DL, pod disruption budget to prevent DU during upgrade/maintenance.  Note that Kubernetes has support for "planned" node maintenance operations, e.g. `kubectl drain` ([ref](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/)).  Such operations respect the pod disruption budget.

For a conceptual overview, please read the [Disruptions](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/) section of the Kubernetes documentation.

**Comment by EronWright** [comment]
Also related to #61 since `NodePort` necessitates anti-affinity of segment stores.

**Comment by adrianmo** [comment]
Based on the [Pravega deployment documentation](http://pravega.io/docs/latest/deployment/manual-install/), the minimum recommended service layout in a 3-node cluster is the following:

|                       | Node 1 | Node 2 | Node 3 |
|-----------------------|--------|--------|--------|
| Zookeeper             |   X    |   X    |   X    |
| Bookkeeper            |   X    |   X    |   X    |
| Pravega Controller    |   X    |   X    |        |
| Pravega Segment Store |   X    |   X    |   X    |


This deployment can tolerate the temporary failure of one node if the Segment Store ledger replication factor is set to 2. It will take some time for the Segment Store to detect and recover from the failure, but eventually the affected segments will be reassigned to the available instances.

### [Pod Disruption Budget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/)

Pod Disruption Budget is a Kubernetes feature that limits the number of pods of a replicated application that are down simultaneously from _voluntary disruptions_, like updating a pod template, directly deleting a pod by accident, draining a node for repair or upgrade, etc. 

On the other hand, _involuntary disruptions_ like a hardware failure or a kernel panic can happen any moment and without warning. These type of disruptions are out of the scope and cannot be handled by the Pod Disruption Budget.

My proposal is we limit the number of pods to the recommended minimum for each component. This means that if a Kubernetes administrator needs to evacuate one of the nodes in the example cluster layout above, the Pod Disruption Budget will prevent the termination of pods until a new node is added to the Kubernetes cluster and replacement pods are recreated and started successfully. 

This guarantees that the Pravega cluster never falls below the minimum recommended layout and gives us the ability to lose one node in case of an involuntary disruption. 

Therefore, the `minAvailable` for each component would be:

|                       | `minAvailable` |
|-----------------------|----------------|
| Zookeeper             |       3        |
| Bookkeeper            |       3        |
| Pravega Controller    |       2        |
| Pravega Segment Store |       3        |


### [Pod anti-affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#inter-pod-affinity-and-anti-affinity-beta-feature)

Pod anti-affinity can be leveraged to prevent scheduling more than one instance of a particular component to the same node. For example, in a 3-node cluster without pod anti-affinity we may end up having three Bookkeeper instances in Node 1, and none in Node 2 and 3 (depending on the node pressure).

There are two types of affinity: _preferred_ and _required_. The first one is a soft requirement that gives priority to certain nodes if they meet some conditions; and the second one is a hard requirement that the node must meet, if none meets the requirement, the pod will remain unscheduled until a new node that meets the requirements is added to the cluster.

In Pravega, there's no functional requirement to run components in different nodes, but for better fault tolerance and performance, instances of the same type are recommended to be spread across different nodes. 

My proposal is that for each component type, we define a pod anti-affinity like this:

```
...
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: component
              operator: In
              values:
              - bookie
            - key: pravega_cluster
              operator: In
              values:
              - pravega-cluster-1
          topologyKey: kubernetes.io/hostname
```

### [Multiple zones](https://kubernetes.io/docs/setup/multiple-zones/)

In some platforms, labels with zone information are automatically added to nodes when they are started.

In a multiple-zone cluster, Kubernetes will automatically spread pods of the same type across zones. This is a best-effort placement that might result in an unequal spreading if the zones are heterogeneous (different number of nodes, different types of nodes, etc).

To tell Kubernetes to prioritize the spreading across zones, we can also leverage pod anti-affinity. Below is an example pod anti-affinity rule to spread Bookies across different zones. Since the rule is using a "preferred" requirement, the rule will have no effect if only one zone is available in the cluster.

```
...
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: component
              operator: In
              values:
              - bookie
            - key: pravega_cluster
              operator: In
              values:
              - pravega-cluster-1
          topologyKey: failure-domain.beta.kubernetes.io/zone
```

I would like to have your feedback and start a discussion about these topics.

/cc @EronWright @maddisondavid @fpj
