### ISSUE TITLE
Configure Bookie metrics

### ISSUE THREAD

**Issue by EronWright** [pravega/pravega-operator#63]
The operator should support bookie metrics, notably graphite (as provided by codahale) and prometheus.

Related documentation:
http://bookkeeper.apache.org/docs/4.7.0/admin/metrics/

**Comment by jkhalack** [comment]
For the pravega-operator to support BK metrics, pravega bookkeeper deployment should provide a way to overwrite the default `enableStatistics` and `statsProviderClass` parameters in the `bk_server.conf` file inside the BK docker container, in the same way it is done for the other configurable parameters:  https://github.com/pravega/pravega/blob/master/docker/bookkeeper/entrypoint.sh#L40-L45

**Comment by jkhalack** [comment]
https://github.com/pravega/pravega/issues/3101

**Comment by adrianmo** [comment]
Need to extend the `PravegaCluster` API to support adding custom BookKeeper configuration that will be passed to the BookKeeper pod in the form of environment variables. Similar to what we are currently doing with [Pravega options](https://github.com/pravega/pravega-operator/blob/master/example/cr-detailed.yaml#L56).

e.g. if we want to set `enableStatistics=true` and `statsProviderClass=org.apache.bookkeeper.stats.codahale.CodahaleMetricsProvider`.

```

apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "pravega"
spec:
  bookkeeper:
    image:
      repository: pravega/bookkeeper
      tag: latest
      pullPolicy: IfNotPresent

    replicas: 3

    options:
      enableStatistics: true
      statsProviderClass: org.apache.bookkeeper.stats.codahale.CodahaleMetricsProvider
...
```

The operator will read the `options` block as a key-value list and set them in the config map for BK after prepending the `BK_` prefix to the option keys, e.g. `BK_enableStatistics` and `BK_statsProviderClass`).

Ref: https://github.com/apache/bookkeeper/blob/master/docker/README.md#environment-variable-names-that-mostly-used-for-your-configuration
