### ISSUE TITLE
Allow Authorization to be configured

### ISSUE THREAD

**Issue by maddisondavid** [pravega/pravega-operator#68]
Currently the operator configures Pravega with authorization turned off.  This should be modified to allow authorization to be configured and turned on.

An example from Pravega controller configuration: https://github.com/pravega/pravega-operator/blob/2fd310899a66a47f1a25da5faef416395632b5e6/pkg/pravega/pravega_controller.go#L114-L125

**Comment by maddisondavid** [comment]
This can be configured using the `options` part of the `PravegaCluster` specification:

```
  pravega:
   ...
   ...
    options:
      metrics.enableStatistics: "true"
      metrics.statsdHost: "telegraph.default"
      metrics.statsdPort: "8125"
      AUTHORIZATION_ENABLED: "true"
    
```
