### ISSUE TITLE
Support Pravega upgrades

### ISSUE THREAD

**Issue by fpj** [pravega/pravega-operator#81]
As new Pravega versions are released, users will want to upgrade to a newer version. The operator should provide support for such upgrades with minimal to no disruption.

**Comment by adrianmo** [comment]
Currently, the `PravegaCluster` resource spec allows users full control on the Docker image being used for Bookkeeper and Pravega. E.g.:

```
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "example"
spec:
  ...
  bookkeeper:
    ...
    image:
      repository: pravega/bookkeeper
      tag: latest
      pullPolicy: Always

  pravega:
    ...
    image:
      repository: pravega/pravega
      tag: latest
      pullPolicy: Always
```

Users can use any Docker image and tag, even non-related Pravega images, non-existent images, or incompatible images. Risking the Pravega cluster deployment and stability over time. Moreover, this configuration flexibility also will pose a problem when we implement the upgrade feature.

As part of an upgrade process, we want to make sure that:

- The user upgrades to an official and validated Docker image repository and tag. 
- The version we are upgrading to is compatible with the current version (e.g. allow upgrade to `0.4.0` only if coming from `0.3.2`).
- The upgrade process can be rolled back if any issue occurs.
- The operator should be able to run custom migration tasks when upgrading between specific versions (e.g. schema changes).

However, the above goals conflict with flexibility of the current `PravegaCluster` spec. My idea is to get rid of the `image` sections and create a top-level `version` field to allow users to specify the Pravega version they want to run. E.g.:

```
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "example"
spec:
  ...
  version: 0.4.0
  bookkeeper:
    ...
  pravega:
    ...
```

Internally, the operator will validate if the given `version` is a valid version and fetch the associated Docker images for that version. This allows us to have gain control of the software version being used, avoiding human errors and incompatibilities between Pravega and BK.

In an upgrade process, the operator will also be able to easily validate the version change and run any migration task that is needed. 

Moreover, support for new Pravega versions will be incorporated in a controlled manner, where we will be able to test them and validate them before accepting them as valid versions in the operator.

@fpj @EronWright @shrids @Tristan1900 can you share your thoughts?
