### ISSUE TITLE
Set default values when not specified

### ISSUE THREAD

**Issue by adrianmo** [pravega/pravega-operator#88]
The operator should use default values when they are not set in the manifest. 

The proposed default values are the following:

```
spec:
  zookeeperUri: zk-client:2181

  externalAccess:
    enabled: false

  bookkeeper:
    image:
      repository: pravega/bookkeeper
      tag: latest
      pullPolicy: Always

    replicas: 3

    storage:
      ledgerVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi

      journalVolumeClaimTemplate:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi

    autoRecovery: true

  pravega:
    controllerReplicas: 1
    segmentStoreReplicas: 3

    debugLogging: false

    cacheVolumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 20Gi

    image:
      repository: pravega/pravega
      tag: latest
      pullPolicy: Always

    tier2:
      filesystem:
        persistentVolumeClaim:
          claimName: pravega-tier2
```

This will allow users to partially fill the manifest or even leave the specs empty. The below example should be a valid manifest that would use default values:

```
apiVersion: "pravega.pravega.io/v1alpha1"
kind: "PravegaCluster"
metadata:
  name: "pravega"
```
